### ISSUE TITLE
FeatureReq: Debug & Output Implied-Function Highlighting

### ISSUE THREAD

**Issue by DyoungMCWI** [AgileBIM/FabCOD#18]
**Describe the solution you'd like**
A couple functions like DEBUG and OUTPUT can be used with or without parenthesis. Without parenthesis, they do not highlight. Not sure if there's a way to define the objects so that they do.

**Describe possible alternatives you've considered**
Perhaps a specialty keywords list/object that highlights the same color so if it's typed without parenthesis, the syntax is highlighted via keywords or if typed with parenthesis it's highlighted via the functions.

**Additional context**
Not sure if my suggestion is the proper way to handle this. Also not sure how to make the color coding the same for the DEFUG function if that was the proper way or if there's other parts of code that would need to be updated (ItemParser, etc.)

See the following Autodesk Screencast for an example of the issue...
https://autode.sk/3tdttcu

**Comment by JD-Howard** [comment]
To make a another section just for this special case, you could edit the file you have to update for you open PR.

Find this section:
https://github.com/AgileBIM/FabCOD/blob/943b6275f65086a8ec0d73ef468d00d36ed85906/configurations/codscript-tmLanguage.template.json#L50-L54

Make it read:
```
{
	"comment": "Global Functions",
	"name": "markup.bold",
	"match": "\\b((?i)%%%FUNCTIONS%%%)(?=\\()"
},
{
	"comment": "Passive Functions",
	"name": "markup.bold",
	"match": "\\b((?i)DEBUG|OUTPUT)\\b"
},
```
This may not update the Mouse Hover functionality, but I am not entirely sure I care.

**Comment by DyoungMCWI** [comment]
Updated per your guidance (after I fixed my language template snafu)

**Comment by JD-Howard** [comment]
Looked good, so this is done.
