### ISSUE TITLE
Bug Report: INCLUDE function lists all file (not just COD)

### ISSUE THREAD

**Issue by DyoungMCWI** [AgileBIM/FabCOD#19]
**Describe the bug**
INCLUDE function file list shows all files.

**Expected behavior**
INCLUDE function should only show COD files.

**Screenshots**
![2021-03-16_20-41-32](https://user-images.githubusercontent.com/43396040/111412441-aa499780-8699-11eb-9a71-6c391bec4000.png)

**Additional context**
Tested against Build 0.1.0

**To Reproduce**
1. Add Files of various types to folder where COD Scripts exist.
2. Edit one of the COD Scripts in that folder and type an INCLUDE function
3. Notice the resulting file list shows all the files, not just those with a COD extension.

**Comment by JD-Howard** [comment]
@DyoungMCWI, I did not rebuild the VLX, but please test this when you get a chance and if you agree it is corrected, then close this issues.

**Comment by DyoungMCWI** [comment]
Looks to be resolved. Nice work. Apologies for the delay in testing. Some issues with compiling the VSIX which I was able to finally resolve on my new system.
