### ISSUE TITLE
FeatureReq: RUN function should show same file list as INCLUDE does

### ISSUE THREAD

**Issue by DyoungMCWI** [AgileBIM/FabCOD#20]
**Describe the solution you'd like**
INCLUDE function displays a list of files to reference. The RUN function does not but should so the same thing. It's syntax is the same except it immediately executes the code on those COD scripts.

**Describe possible alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JD-Howard** [comment]
@DyoungMCWI, I did not rebuild the VLX, but please test this when you get a chance and if you agree it is corrected, then close this issues.

**Comment by DyoungMCWI** [comment]
Looks to be resolved. Nice work. Apologies for the delay in testing. Some issues with compiling the VSIX which I was able to finally resolve on my new system.
